name: Coin Premium Update

on:
  schedule:
    - cron: '5,35 * * * *'
  workflow_dispatch:

permissions: # 깃허브에 파일을 쓸 수 있는 권한 추가
  contents: write

jobs:
  update-coin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_coin.py
      - name: Commit and Push # 변경된 JSON 파일을 깃허브에 반영
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add coin_data.json
          git commit -m "Update coin data" || exit 0
          git push
